# Configuration file for signature detection model
# This file contains all training and evaluation parameters

model:
  architecture: "yolo11n.pt"  # Base YOLO model
  name: "signature_detector"  # Model name
  
training:
  # Core training parameters
  epochs: 5  # Minimal for low-end devices (use 50 for full training)
  batch_size: 4  # Small batch for low-end devices (use 16-32 for full training)
  learning_rate: 0.001
  
  # Image settings
  image_size: 640
  
  # YOLO-specific parameters
  single_cls: true  # Single class detection (signature)
  
  # Loss weights (optimized for signature detection)
  box_loss_weight: 7.5
  cls_loss_weight: 0.5
  dfl_loss_weight: 1.5
  
  # Optimizer settings
  optimizer: "AdamW"
  lr_scheduler: "cosine"
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  
  # Regularization
  weight_decay: 0.0005
  momentum: 0.937
  
  # Data augmentation
  hsv_h: 0.015    # Hue augmentation
  hsv_s: 0.7      # Saturation augmentation
  hsv_v: 0.4      # Value augmentation
  degrees: 0.0    # Rotation (disabled for signatures)
  translate: 0.1  # Translation
  scale: 0.5      # Scale augmentation
  shear: 0.0      # Shear (disabled for signatures)
  perspective: 0.0 # Perspective (disabled for signatures)
  flipud: 0.0     # Vertical flip (disabled)
  fliplr: 0.5     # Horizontal flip
  mixup: 0.0      # Mixup augmentation (disabled)
  copy_paste: 0.0 # Copy-paste augmentation (disabled)
  
  # Early stopping
  patience: 10    # Early stopping patience
  
  # Validation
  val_freq: 1     # Validation frequency (every epoch)
  
  # Device settings
  device: "auto"  # Use GPU if available, otherwise CPU
  workers: 4      # Number of data loading workers

data:
  config_path: "data/signature/data.yaml"
  num_classes: 1
  class_names: ["signature"]
  
  # Data paths (relative to data.yaml)
  train_path: "train"
  val_path: "val"
  
  # Data validation
  verify_images: true
  cache: false    # Disable caching for now

evaluation:
  # Confidence and IoU thresholds
  conf_threshold: 0.25
  iou_threshold: 0.5
  
  # Evaluation settings
  save_json: true
  save_plots: true
  save_report: true
  
  # Testing settings
  test_individual_images: true
  num_test_images: 10
  
  # Metrics to track
  metrics:
    - "mAP@0.5"
    - "mAP@0.5:0.95"
    - "precision"
    - "recall"
    - "F1"

inference:
  # Inference parameters
  conf_threshold: 0.5   # Higher confidence for production
  iou_threshold: 0.5
  max_detections: 100
  
  # Output settings
  save_predictions: true
  save_visualizations: true
  output_dir: "predictions"

logging:
  level: "INFO"
  log_file: "training.log"
  
  # Weights & Biases integration (optional)
  wandb:
    enabled: false
    project: "signature-detection"
    entity: null
    
  # TensorBoard logging
  tensorboard:
    enabled: true
    log_dir: "runs"

# Environment settings
environment:
  random_seed: 42
  deterministic: false  # Set to true for reproducible results (slower)
  
# Paths
paths:
  models_dir: "models"
  results_dir: "results"
  logs_dir: "logs"
  
# Advanced settings
advanced:
  # Model pruning (experimental)
  pruning:
    enabled: false
    sparsity: 0.3
  
  # Quantization (experimental)
  quantization:
    enabled: false
    backend: "fbgemm"
